2017-07-23 08:23:50,029 - sqlalchemy.pool.QueuePool - pool.py[line:643] - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2542, in do_rollback
    dbapi_connection.rollback()
OperationalError: (2006, 'MySQL server has gone away')
2017-07-23 08:23:50,031 - sqlalchemy.pool.QueuePool - pool.py[line:643] - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2542, in do_rollback
    dbapi_connection.rollback()
OperationalError: (2006, 'MySQL server has gone away')
2017-07-23 08:23:50,031 - sqlalchemy.pool.QueuePool - pool.py[line:643] - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2542, in do_rollback
    dbapi_connection.rollback()
OperationalError: (2006, 'MySQL server has gone away')
2017-07-23 08:23:50,031 - sqlalchemy.pool.QueuePool - pool.py[line:643] - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2542, in do_rollback
    dbapi_connection.rollback()
OperationalError: (2006, 'MySQL server has gone away')
2017-07-23 08:23:50,031 - sqlalchemy.pool.QueuePool - pool.py[line:643] - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2542, in do_rollback
    dbapi_connection.rollback()
OperationalError: (2006, 'MySQL server has gone away')
2017-07-23 18:51:43,492 - tornado.access - web.py[line:1971] - WARNING - 405 GET /master-status (140.205.225.202) 1.99ms
2017-07-23 18:54:50,791 - tornado.access - web.py[line:1971] - WARNING - 405 GET /about/ (140.205.225.202) 1.92ms
2017-07-24 01:47:33,691 - tornado.access - web.py[line:1971] - WARNING - 405 GET http://www.server110.com/ (122.228.208.106) 2.02ms
2017-07-24 01:47:33,778 - tornado.access - web.py[line:1971] - WARNING - 405 CONNECT www.linode.com:443 (122.228.208.106) 1.38ms
2017-07-24 01:47:33,857 - tornado.access - web.py[line:1971] - WARNING - 405 CONNECT www.linode.com:443 (122.228.208.106) 2.12ms
2017-07-24 01:47:33,935 - tornado.access - web.py[line:1971] - WARNING - 405 CONNECT www.linode.com:443 (122.228.208.106) 0.97ms
2017-07-24 01:50:19,486 - tornado.access - web.py[line:1971] - WARNING - 405 CONNECT www.baidu.com (120.32.71.1) 1.10ms
2017-07-24 01:50:20,586 - tornado.access - web.py[line:1971] - WARNING - 405 GET http://www.123cha.com (60.216.140.32) 1.95ms
