2017-07-31 23:33:57,023 - tornado.access - web.py[line:1971] - WARNING - 404 GET /robots.txt (127.0.0.1) 1.47ms
2017-07-31 23:33:59,729 - sqlalchemy.pool.QueuePool - pool.py[line:643] - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2542, in do_rollback
    dbapi_connection.rollback()
OperationalError: (2006, 'MySQL server has gone away')
2017-08-01 03:52:02,100 - tornado.access - web.py[line:1971] - WARNING - 405 GET http://www.qq.com/404/search_children.js (120.132.3.151) 2.24ms
2017-08-01 08:55:41,771 - sqlalchemy.pool.QueuePool - pool.py[line:643] - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2542, in do_rollback
    dbapi_connection.rollback()
OperationalError: (2006, 'MySQL server has gone away')
2017-08-01 09:21:01,025 - tornado.access - web.py[line:1971] - WARNING - 405 GET /phpmyadmin (114.115.207.143) 3.14ms
2017-08-01 09:21:01,071 - tornado.access - web.py[line:1971] - WARNING - 405 GET /phpmyadmin (114.115.207.143) 1.83ms
2017-08-01 18:45:47,871 - tornado.access - web.py[line:1971] - WARNING - 405 GET /master-status (140.205.201.34) 2.01ms
2017-08-01 19:10:09,234 - tornado.access - web.py[line:1971] - WARNING - 405 GET /about/ (140.205.201.34) 1.98ms
