2017-08-13 08:49:40,151 - sqlalchemy.pool.QueuePool - pool.py[line:643] - ERROR - Exception during reset or similar
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py", line 2542, in do_rollback
    dbapi_connection.rollback()
OperationalError: (2006, 'MySQL server has gone away')
2017-08-13 12:01:13,119 - tornado.access - web.py[line:1971] - WARNING - 405 GET http://clientapi.ipip.net/echo.php?info=1234567890 (139.162.81.62) 2.06ms
2017-08-13 17:01:50,066 - tornado.access - web.py[line:1971] - WARNING - 405 GET /master-status (140.205.201.37) 2.12ms
2017-08-13 17:16:35,334 - tornado.access - web.py[line:1971] - WARNING - 405 GET /about/ (140.205.201.37) 1.95ms
2017-08-13 23:48:16,963 - tornado.access - web.py[line:1971] - WARNING - 404 GET /robots.txt (127.0.0.1) 1.55ms
2017-08-14 01:16:02,882 - tornado.access - web.py[line:1971] - WARNING - 404 GET /robots.txt (127.0.0.1) 1.50ms
